# Generated by Django 5.1.5 on 2025-01-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_best_of_legs_game_best_of_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('dart_one', models.CharField(max_length=5, null=True)),
                ('dart_two', models.CharField(max_length=5, null=True)),
                ('dart_three', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
