# Generated by Django 5.1.5 on 2025-01-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_checkoutlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_throws', models.IntegerField(default=0)),
                ('three_dart_avg', models.FloatField(default=0.0)),
                ('first_nine_avg', models.FloatField(default=0.0)),
                ('checkout_rate', models.FloatField(default=0.0)),
                ('best_dart_leg', models.IntegerField(default=0)),
                ('legs_won', models.IntegerField(default=0)),
                ('sets_won', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='GameStateHistory',
        ),
        migrations.AddField(
            model_name='game',
            name='raw_game_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player'),
        ),
        migrations.AlterUniqueTogether(
            name='gamestatistics',
            unique_together={('game', 'player')},
        ),
    ]
