# Generated by Django 5.1.5 on 2025-01-29 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_name_player_full_name_player_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamestatistics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raw_leg_data', models.JSONField()),
                ('leg_number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='games.game')),
                ('players', models.ManyToManyField(related_name='legs', to='games.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_legs', to='games.player')),
            ],
        ),
        migrations.CreateModel(
            name='LegStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_throws', models.IntegerField(default=0)),
                ('three_dart_avg', models.FloatField(default=0.0)),
                ('first_nine_avg', models.FloatField(default=0.0)),
                ('checkout_rate', models.FloatField(default=0.0)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.leg')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
            ],
        ),
    ]
